### ISSUE TITLE
nullable dictionary members don't seem necessary

### ISSUE THREAD

**Issue by domenic** [WICG/storage-buckets#114]
```webidl
dictionary StorageBucketOptions {
  boolean persisted = false;
  unsigned long long? quota = null;
  DOMHighResTimeStamp? expires = null;
};
```

These latter two dictionary members are already optional. It's better to not make them nullable, as that just introduces two different types of optional-ness into the platform.

**Comment by domenic** [comment]
https://github.com/WICG/storage-buckets/issues/99 is related.

**Comment by annevk** [comment]
@evanstade I don't think you fixed this. You kept them as nullable.

I can't reopen unfortunately.

cc @ayuishii

**Comment by inexorabletash** [comment]
A relevant tangent - `StorageBucket` has:

```webidl
Promise<DOMHighResTimeStamp?> expires();
```

So if a bucket is created without expires (by not passing `expires` member or passing explicit `undefined`), this accessor will resolve to `null`, which seems like a bit of a mismatch. Should this be `Promise<(DOMHighResTimeStamp or undefined)>` instead?

**Comment by evanstade** [comment]
I looked at changing the return type of `expires()` to what @inexorabletash suggested but Blink's IDL bindings generator doesn't support this usage of undefined: crbug.com/1293259

> If you expect people to often feed the return value of [...]

I don't think we expect it in particular but it's hard to be sure that it wouldn't be done.

> we've decided to deal with this by allowing the dictionary member to be nullable after all.

So shall we just remove the default value from `expires` (as done in #115 )? We could still remove nullabliity from `quota` but that would feel inconsistent next to `expires`.

**Comment by domenic** [comment]
I think removing nullability is still the right path.
