### ISSUE TITLE
Consider using DOMHighResTimestamp instead of DOMTimeStamp

### ISSUE THREAD

**Issue by yoavweiss** [WICG/storage-buckets#38]
We're considering our options RE `DOMTimeStamp`, and wondering what it's used for. It seems less well-defined than `DOMHighResTimestamp`. Would y'all consider switching over?

See https://github.com/heycam/webidl/issues/2 for discussion.

**Comment by evanstade** [comment]
This should be doable.

**Comment by ayuishii** [comment]
Closing since I think this is resolved now. Spec now reflects this and is used in the IDL in Chromium.
