### ISSUE TITLE
How does user agent grant persistent permission

### ISSUE THREAD

**Issue by zeroliu** [WICG/storage-buckets#6]
Firefox and Chrome currently provide different mechanisms for granting persistent permission. Applications have to provide different user flows to guide users through this process based on user agent. Is there a plan to standardize this process across user agents in the multi storage buckets world?

**Comment by evanstade** [comment]
This doesn't really seem like a buckets-related question, in that the Buckets API doesn't change the landscape in a way that would suggest FF or Chromium needs to alter their mechanism for persistence granting, but I'll still take a stab at the answer: I don't believe so. Different browser vendors will have differing opinions on what constitutes sufficient safety or privacy or usability, and must have the flexibility to innovate on UI in that domain.
