### ISSUE TITLE
What's expected for zero quota?

### ISSUE THREAD

**Issue by nathanmemmott** [WICG/storage-buckets#61]
If we open a bucket with quota set to zero, should we expect it to:

1.  Reject the open promise.
2.  Ignore it as if it hadn't been set (meaning its quota would equal the storage key's quota).
3.  Allow it to be set to zero and nothing can be stored in it.

I can't see a reason to allow zero quota buckets. If we don't allow it, rejecting seems better than ignoring because you probably don't want to open a zero quota bucket and get the max storage key quota instead.

**Comment by evanstade** [comment]
I agree that zero doesn't make sense. The spec currently states `If |quota| is less than or equal to zero, then return failure.` Ultimately that will lead to a TypeError rejection. Unless spec reviewers have a different opinion, let's go with this behavior.
